# Site settings
title: Geekfem Hamburg
email: geekfem@hamburg.ccc.de
description: > # this means to ignore newlines until "baseurl:"
  Because we can!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geekfem.net" # the base hostname & protocol for your site
twitter_username: geekfem_
github_username:  geekfem

# Build settings
markdown: kramdown
